FROM python:3

WORKDIR /app

COPY backend/requirement.txt /app/

RUN pip install --no-cache-dir -r requirement.txt

COPY . .

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "5000", "--reload"]
